export enum GIT_TYPE {
  GITHUB = "GITHUB",
  GITLAB = "GITLAB",
  BITBUCKET = "BITBUCKET",
}

export enum ENVIRONMENT {
  DEVELOPMENT = "DEVELOPMENT",
  STAGING = "STAGING",
  PRODUCTION = "PRODUCTION",
}
export enum INTEGRATION_PROVIDERS {
  SLACK = "SLACK",
  SENTRY = "SENTRY",
  DISCORD = "DISCORD",
  ONBOARDBASE = "ONBOARDBASE",
  CONTENTFUL = "CONTENTFUL",
  NOVU = "NOVU",
  NETLIFY = "NETLIFY",
}

export enum INTEGRATION_TYPES {
  MESSAGING = "MESSAGING",
  ERROR_TRACKING = "ERROR_TRACKING",
  SECURITY = "SECURITY",
  ANALYTICS = "ANALYTICS",
  STORAGE = "STORAGE",
  LOGGING = "LOGGING",
  DEVTOOLS = "DEVTOOLS",
  MONITORING = "MONITORING",
  CMS = "CMS",
}

export enum OAUTH_PERMISSIONS {
  READ_USER = "read_user",
  READ_PROJECT = "read_project",
  UPDATE_CREDENTIALS = "update_credentials",
}

export enum ROLES {
  CREATOR = "CREATOR",
  MEMBER = "MEMBER",
}

export enum PROJECT_STATUS {
  INACTIVE = "INACTIVE",
  ACTIVE = "ACTIVE",
  INPROGRESS = "INPROGRESS",
  FAILED = "FAILED",
  PENDING = "PENDING",
}
