export enum GIT_TYPE {
  GITHUB = "GITHUB",
  GITLAB = "GITLAB",
  BITBUCKET = "BITBUCKET",
}
export enum INTEGRATION_TYPE {
  SLACK = "SLACK",
  ASANA = "ASANA",
  SENTRY = "SENTRY",
  DOPPLER = "DOPPLER",
  CONTENTFUL = "CONTENTFUL",
}
